import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Header from '@/components/header'
import { Inter_Tight } from 'next/font/google'
import { ToastContainer } from 'react-toastify'
import Sidebar from '@/components/sidebar'
import SidebarSheet from '@/components/sidebar-sheet'

export const interTight = Inter_Tight({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-title', // variável CSS
})

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="pt-BR"
      className={` ${interTight.variable} bg-background text-foreground`}
    >
      <body className="bg-background text-foreground min-h-screen antialiased">
        <div className="flex flex-col items-center bg-black ">
          <div className="h-full w-[98%] rounded-t-xl ">
            <div className="bg-white rounded-t-xl mt-2 flex">
              {/* Sidebar fixa */}
                <Sidebar />
                <main className="flex-1">

                  {/* Mobile */}
                  <div className="md:hidden flex-1 md:ml-64">
                    <SidebarSheet />
                  </div>

                  {children}
                </main>
              </div>
            </div>
          </div>
      </body>
    </html>
  )
}
