import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Header from '@/components/header'
import { Inter_Tight } from 'next/font/google'
import { ToastContainer } from 'react-toastify'
import Sidebar from '@/components/sidebar'
import SidebarSheet from '@/components/sidebar-sheet'
import { ClientProvider } from './ClienteProvider'

export const interTight = Inter_Tight({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-title', // variável CSS
})

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="pt-BR"
      className={` ${interTight.variable} bg-background text-foreground`}
    >
      <body className="bg-background text-foreground min-h-screen antialiased">
        <ClientProvider>
          <div className="flex flex-col items-center bg-black">
            <div className="h-full w-[98%] rounded-t-xl">
              <div className="mt-2 flex rounded-t-xl bg-gray-50">
                {/* Sidebar fixa */}
                <Sidebar />
                <main className="flex-1">
                  {/* Mobile */}
                  <div className="sticky top-0 h-14 rounded-t-2xl border-b border-gray-300 bg-gray-50 shadow-2xs md:hidden">
                    <SidebarSheet />
                  </div>
                  <Header />
                  {children}
                </main>
              </div>
            </div>
          </div>
        </ClientProvider>
      </body>
    </html>
  )
}
